### ISSUE TITLE
Great job simplifying the CSS. It can also be simplified for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [chiconstruct/prj-rev-bwfs-dasmoto#5]
Great job simplifying the CSS code for several shared properties. You can simplify it further for the font-weight property as well. You can do so like

```css
h2, span {
  font-weight: bold;
}
```
